### ISSUE TITLE
Static Weather Not Displaying

### ISSUE THREAD

**Issue by Danrarbc** [robbydyer/sports#238]
Leaving the scroll mode set to true as is default works just fine. But when I set it to false the board seems to try to load it but then immediately starts the slideshow again and ends up on my first board. 

```
weatherConfig:
  enabled: true

  # Set this to true if you want temps in Celsius
  metricUnits: false

  # Set this to true to show the weather board in between every other board
  showBetween: false

  scrollMode: true

  # Go to openweathermap.org and register an account, then put your API key here
  apiKey: "****"

  # Enter your Zip code here
  zipCode: 63042

  # Country code
  country: US
  # Show the current forecast

  currentForecast: true

  # Show the hourly forecast
  hourlyForecast: false

  # Show the daily forecast
  dailyForecast: true

  # Number of days to show in daily forecast
  dailyNumber: 2

  # Number of days to show in hourly forecast
  hourlyNumber: 3

  # Set the spacing between the tickers in scroll mode. Default is 10
  tightScrollPadding: 10

  # Delay between each screen in non-scroll mode
  boardDelay: "10s"

  scrollDelay: "100ms"
```
Running the command directly in the terminal so I can see the log doesn't really seem to look any different whether it's set to true or false.
