### ISSUE TITLE
24h Clock

### ISSUE THREAD

**Issue by kif23** [robbydyer/sports#301]
Using this from the EU.. we need an option for 24h

**Comment by robbydyer** [comment]
Sure thing, I'll get that option added.

**Comment by robbydyer** [comment]
Latest version now has an option for this. Under `clockConfig` in your config file, set `enable24Hour: true`. See https://github.com/robbydyer/sports/blob/master/sportsmatrix.conf.example#L123

https://github.com/robbydyer/sports/releases/tag/v0.0.88

**Comment by kif23** [comment]
installed [0.0.88beta1](https://github.com/robbydyer/sports/releases/tag/v0.0.88) via 

`curl https://raw.githubusercontent.com/robbydyer/sports/master/script/beta-install.sh | sudo bash `

/etc/sportsmatrix.conf looks like

```
# Clock Board
clockConfig:
  enabled: true

  # Set this to true to show the clock board in between every other board
  showBetween: false

  boardDelay: "5s"

  # Enable 24 Hour clock
  enable24Hour: true
```
restarted the service and pi, but still 12h AM/PM in clock card.
